apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cnj-tracing-downstream.fullname" . }}
  labels:
    {{- include "cnj-tracing-downstream.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.pod.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cnj-tracing-downstream.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cnj-tracing-downstream.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cnj-tracing-downstream.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pod.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.container.main.securityContext | nindent 12 }}
          image: "{{ .Values.container.main.image.repository }}:{{ .Values.container.main.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.main.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.main.ports.http.number }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.container.main.probes.liveness.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.container.main.probes.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.container.main.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: {{ .Values.security.oidc.jwksUri | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.security.oidc.issuer | quote }}
            - name: OPENTRACING_JAEGER_ENABLED
              value: {{ .Values.tracing.enabled | quote }}
            - name: OPENTRACING_JAEGER_UDP_SENDER_HOST
              value: {{ .Values.tracing.jaeger.agent.host | quote }}
            - name: OPENTRACING_JAEGER_UDP_SENDER_PORT
              value: {{ .Values.tracing.jaeger.agent.port | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
